version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: mysql_db
      REDIS_HOST: redis_cache
      DATABASE_USER: root
      DATABASE_PASSWORD: rootpassword
      DATABASE_NAME: user_mapping_db
      DATABASE_PORT: 3306
    depends_on:
      - mysql_db
      - redis_cache

  mysql_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_mapping_db
    ports:
      - "3306:3306"
    expose:
      - "3306"

  redis_cache:
    image: redis:alpine
    ports:
      - "6379:6379"
